#!/bin/sh

# (C) 2015-2016 Cryptopunks.org <Xa2ee at cryptopunks dot org>

# Minimalistic and secure Wifi manager 

# Needed packages: openvpn wpasupplicant macchanger

MINSECWIFI_CONF="minsecwifi.conf"

if [ ! $EDITOR ]; then
    EDITOR=vim
fi

usage() {
        echo "Usage:"
        echo "$0 -s [scan networks] -c [connect] -es [edit wpa_supplicant.conf] -em [edit minsecwifi.conf]"
        exit
}

checkperm() {
    if [[ "$USER" != 'root' ]]; then
        echo "Sorry, you need to run this as root"
        exit
    fi
}

if [ -f minsecwifi.conf ]; then
. ./minsecwifi.conf
else 
    echo -e "I need configuration file \"minsecwifi.conf\".\n"
    echo -e "Please run:\n\n$ wget https://raw.githubusercontent.com/cryptopunks/minsecwifi/master/minsecwifi.conf.sample --no-check-certificate -O minsecwifi.conf"
    echo -e "$ mv minsecwifi.conf.sample minsecwifi.conf\n"
    echo "and edit \"minsecwifi.conf\""
    exit
fi


if [ $# -ne 1 ]; then
    usage
fi

if [ $1 = "-s" ]; then
    checkperm
    iw dev $WIFI_DEV scan | grep -i ssid | sed s/SSID://
    exit
elif [ $1 = "-c" ]; then
    checkperm
    echo "Connecting"
elif [ $1 = "-es" ]; then
    checkperm
    $EDITOR $WPA_CONF
    exit
elif [ $1 = "-em" ]; then
    $EDITOR $MINSECWIFI_CONF
    exit
else
    usage
fi

# killing old processes
(kill -9 `ps aux | grep openvpn | awk {'print $2'}`) 2> /dev/null
(kill -9 `ps aux | grep wpa_supplicant | awk {'print $2'}`) 2> /dev/null
(kill -9 `ps aux | grep dhclient | awk {'print $2'}`) 2> /dev/null

echo "Unblock Wifi-device: "
rfkill unblock 0 && echo OK

echo "Wifi interface down: "
ifconfig $WIFI_DEV down && echo OK

echo "Change MAC-address: "
macchanger -r  $WIFI_DEV && echo OK

echo "Wifi interface up:"
ifconfig $WIFI_DEV up && echo OK

echo "Connecting Wifi: "
rm -f /var/run/wpa/$WIFI_DEV
wpa_supplicant -B -i $WIFI_DEV -c $WPA_CONF && echo OK

echo "Get DHCP address:"
dhclient $WIFI_DEV && echo OK

echo "Rewrite DNS: "
echo -e $DNS > /etc/resolv.conf
echo OK

echo "Connecting VPN: "
openvpn --config $OVPN_CONF && echo OK
